pipeline {

    agent any
    tools{
        maven 'Maven 3.6.1'
    }

    stages{
        stage('build'){
            echo 'Compiling worker app'
            dir('worker'){
            sh 'mvn compile'
            }
        }
    }
        stage('test'){
            echo 'Running Unit tests on worker app'
            
        }
    }
        stage('package'){
            echo 'Packaging worker app'
        }
    }
}

post {
    always{
        echo "Build pipeline for the worker is complete"
    }
}